package com.example.myapplication.local.core

enum class PantallaActual {
    LOGIN,
    CARGANDO_SESION,
    REGISTRO,
    INFORMACION,
    CONTACTO,

    SELECCION_PARENT_CIA,
    SELECCION_CIA,

    FILTROS_MONITOREO,
    LISTA_MONITOREOS,
    MAPA_MONITOREO,
    REGISTRO_PUNTO_MONITOREO,
    REPORTE_MONITOREO,
    PERFIL_USUARIO,

    ADMIN_HOME,
    ADMIN_MONITOREOS,
    ADMIN_CATALOGOS,
    ADMIN_GESTION_AGRICOLA
}
